### ISSUE TITLE
Reuse in Udacity class?

### ISSUE THREAD

**Issue by dhruvp** [skeate/cs6601-gui#1]
Hey Jonathan!

My name is Dhruv and I work on the AI programs at Udacity. We're using the isolation project in our upcoming AI Nanodegree and would love to reuse your visualization code so people can see their AI actually move. Is this something you'd be ok with? We'd be sure to cite you on all the visualization files.

You can reach out to me at dhruv@udacity.com if you have more questions.

Thank you! 

Dhruv

**Comment by skeate** [comment]
Absolutely! I'll add a license, since apparently I forgot to before.
